micronaut.application.name=amazon-reviews
micronaut.server.port=8080
micronaut.server.context-path=/

hevmesh.base-url=http://localhost:9090

logger.levels.com.example.amazonreviews=DEBUG
logger.levels.io.micronaut.http.server=TRACE
